### PR TITLE
aux auto bid and price heuristics

### PR DESCRIPTION
**Pull request by geojak**
this commit does two things
1. it implements auto bid just like auto buy
2. it has some minimum pricing heuristics when posting items. this behavoiur actiaves when the post bid price is set to 0, the buyout price behaves like a minimum

### CODE REVIEW

**Comment by geojak** [comment]
i added also a keybind and firther improved the auto pricing heuristic.

**Comment by shirsig** [comment]
Hey geojak, thanks for the contribution. I see in your last commit you must've done some formatting change or something that was applied to every file - could you please remove that and limit it to the relevant changes?

**Comment by geojak** [comment]
Hey thx for the reply, in my latest change I accidently uploaded into the wrong folder, so I created an aux folder inside the aux folder on github which then shows all the files as new

**Comment by geojak** [comment]
Maybe I can sent you the zip directly with my current aux? I play on turtle wow, I could drop it in the addon discord there?

**Comment by geojak** [comment]
commit diffs should be fixed now again, check out the updated readme_geojak with a list of changes. i would appreciate if you could review the changes and consider a merge, or even better improve further upon it!

**Comment by shirsig** [comment]
Thanks, looks good now, merging it.

**Pull request merged**
